version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            docker build -t tempvs-ui .
      - run:
          name: Push docker image to Amazon ECR
          command: |
            $(aws ecr get-login --no-include-email --region us-east-2)
            docker push 471216354450.dkr.ecr.us-east-2.amazonaws.com/tempvs-ui:latest
